// Generated file by `flutterfire configure` - customize as needed
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default FirebaseOptions for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.windows)) {
      return windows;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.linux)) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_YOUR_ANDROID_API_KEY_HERE',
    appId: '1:251911023605:android:62c9213a8ede85ed2bcebc',
    messagingSenderId: '251911023605',
    projectId: 'psg-hostel-app',
    storageBucket: 'psg-hostel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_YOUR_IOS_API_KEY_HERE',
    appId: '1:251911023605:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '251911023605',
    projectId: 'psg-hostel-app',
    storageBucket: 'psg-hostel-app.appspot.com',
    iosBundleId: 'com.psgtech.hostelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_YOUR_WINDOWS_API_KEY_HERE',
    appId: '1:251911023605:windows:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '251911023605',
    projectId: 'psg-hostel-app',
    storageBucket: 'psg-hostel-app.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA_YOUR_LINUX_API_KEY_HERE',
    appId: '1:251911023605:linux:YOUR_LINUX_APP_ID',
    messagingSenderId: '251911023605',
    projectId: 'psg-hostel-app',
    storageBucket: 'psg-hostel-app.appspot.com',
  );
}

// IMPORTANT: To regenerate this file with actual credentials:
// 1. Run: `flutterfire configure --project=psg-hostel-app`
// 2. Select the platforms you want to configure
// 3. Choose the project: psg-hostel-app
// 4. This file will be auto-generated with real credentials
