// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBMwfAghaUT0NS82zUZTFnBw9-jydnj60',
    appId: '1:251911023605:web:ec4ec02252da49802bcebc',
    messagingSenderId: '251911023605',
    projectId: 'psg-hostel-app',
    authDomain: 'psg-hostel-app.firebaseapp.com',
    storageBucket: 'psg-hostel-app.firebasestorage.app',
    measurementId: 'G-RFFM02MXJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvglhfOEZ6tGPg6LztCQty7R-KTnHYV9M',
    appId: '1:251911023605:android:62c9213a8ede85ed2bcebc',
    messagingSenderId: '251911023605',
    projectId: 'psg-hostel-app',
    storageBucket: 'psg-hostel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOFNjoNkBhb3JZupxmfxpE4cTBeZHG-1Y',
    appId: '1:251911023605:ios:87720860a9e5a4252bcebc',
    messagingSenderId: '251911023605',
    projectId: 'psg-hostel-app',
    storageBucket: 'psg-hostel-app.firebasestorage.app',
    iosBundleId: 'com.example.hostelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOFNjoNkBhb3JZupxmfxpE4cTBeZHG-1Y',
    appId: '1:251911023605:ios:87720860a9e5a4252bcebc',
    messagingSenderId: '251911023605',
    projectId: 'psg-hostel-app',
    storageBucket: 'psg-hostel-app.firebasestorage.app',
    iosBundleId: 'com.example.hostelApp',
  );
}
